# This file was auto-generated by Fern from our API Definition.

from .resources.agent.client import AgentClient, AsyncAgentClient
from .resources.agent_documents.client import AgentDocumentsClient, AsyncAgentDocumentsClient
from .resources.agent_tools.client import AgentToolsClient, AsyncAgentToolsClient
from .resources.api_token.client import ApiTokenClient, AsyncApiTokenClient
from .resources.auth.client import AsyncAuthClient, AuthClient
from .resources.documents.client import AsyncDocumentsClient, DocumentsClient
from .resources.prompts.client import AsyncPromptsClient, PromptsClient
from .resources.tools.client import AsyncToolsClient, ToolsClient
from .resources.traces.client import AsyncTracesClient, TracesClient
from .resources.user.client import AsyncUserClient, UserClient


class Superagent:
    def __init__(self, *, environment: str, api_key: str):
        self._environment = environment
        self.api_key = api_key
        self.agent = AgentClient(environment=self._environment, api_key=self.api_key)
        self.agent_documents = AgentDocumentsClient(environment=self._environment, api_key=self.api_key)
        self.agent_tools = AgentToolsClient(environment=self._environment, api_key=self.api_key)
        self.auth = AuthClient(environment=self._environment, api_key=self.api_key)
        self.user = UserClient(environment=self._environment, api_key=self.api_key)
        self.api_token = ApiTokenClient(environment=self._environment, api_key=self.api_key)
        self.documents = DocumentsClient(environment=self._environment, api_key=self.api_key)
        self.prompts = PromptsClient(environment=self._environment, api_key=self.api_key)
        self.tools = ToolsClient(environment=self._environment, api_key=self.api_key)
        self.traces = TracesClient(environment=self._environment, api_key=self.api_key)


class AsyncSuperagent:
    def __init__(self, *, environment: str, api_key: str):
        self._environment = environment
        self.api_key = api_key
        self.agent = AsyncAgentClient(environment=self._environment, api_key=self.api_key)
        self.agent_documents = AsyncAgentDocumentsClient(environment=self._environment, api_key=self.api_key)
        self.agent_tools = AsyncAgentToolsClient(environment=self._environment, api_key=self.api_key)
        self.auth = AsyncAuthClient(environment=self._environment, api_key=self.api_key)
        self.user = AsyncUserClient(environment=self._environment, api_key=self.api_key)
        self.api_token = AsyncApiTokenClient(environment=self._environment, api_key=self.api_key)
        self.documents = AsyncDocumentsClient(environment=self._environment, api_key=self.api_key)
        self.prompts = AsyncPromptsClient(environment=self._environment, api_key=self.api_key)
        self.tools = AsyncToolsClient(environment=self._environment, api_key=self.api_key)
        self.traces = AsyncTracesClient(environment=self._environment, api_key=self.api_key)
