# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class AgentType(str, enum.Enum):
    """
    An enumeration.
    """

    REACT = "REACT"
    PLANSOLVE = "PLANSOLVE"
    OPENAI = "OPENAI"

    def visit(
        self,
        react: typing.Callable[[], T_Result],
        plansolve: typing.Callable[[], T_Result],
        openai: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is AgentType.REACT:
            return react()
        if self is AgentType.PLANSOLVE:
            return plansolve()
        if self is AgentType.OPENAI:
            return openai()
