# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic

from ..core.datetime_utils import serialize_datetime
from .app_lib_models_response_document import AppLibModelsResponseDocument


class AppLibModelsResponseAgentDocument(pydantic.BaseModel):
    id: str
    document_id: typing.Optional[str] = pydantic.Field(alias="documentId")
    document: typing.Optional[AppLibModelsResponseDocument]
    agent_id: str = pydantic.Field(alias="agentId")
    created_at: typing.Optional[dt.datetime] = pydantic.Field(alias="createdAt")
    updated_at: typing.Optional[dt.datetime] = pydantic.Field(alias="updatedAt")
    deleted_at: typing.Optional[dt.datetime] = pydantic.Field(alias="deletedAt")

    def json(self, **kwargs: typing.Any) -> str:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().json(**kwargs_with_defaults)

    def dict(self, **kwargs: typing.Any) -> typing.Dict[str, typing.Any]:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().dict(**kwargs_with_defaults)

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True
        json_encoders = {dt.datetime: serialize_datetime}
