# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class DocumentType(str, enum.Enum):
    """
    An enumeration.
    """

    TXT = "TXT"
    PDF = "PDF"
    CSV = "CSV"
    YOUTUBE = "YOUTUBE"
    OPENAPI = "OPENAPI"
    URL = "URL"
    MARKDOWN = "MARKDOWN"
    FIRESTORE = "FIRESTORE"
    PSYCHIC = "PSYCHIC"
    GITHUB_REPOSITORY = "GITHUB_REPOSITORY"
    WEBPAGE = "WEBPAGE"
    STRIPE = "STRIPE"
    AIRTABLE = "AIRTABLE"
    SITEMAP = "SITEMAP"
    NOTION = "NOTION"

    def visit(
        self,
        txt: typing.Callable[[], T_Result],
        pdf: typing.Callable[[], T_Result],
        csv: typing.Callable[[], T_Result],
        youtube: typing.Callable[[], T_Result],
        openapi: typing.Callable[[], T_Result],
        url: typing.Callable[[], T_Result],
        markdown: typing.Callable[[], T_Result],
        firestore: typing.Callable[[], T_Result],
        psychic: typing.Callable[[], T_Result],
        github_repository: typing.Callable[[], T_Result],
        webpage: typing.Callable[[], T_Result],
        stripe: typing.Callable[[], T_Result],
        airtable: typing.Callable[[], T_Result],
        sitemap: typing.Callable[[], T_Result],
        notion: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is DocumentType.TXT:
            return txt()
        if self is DocumentType.PDF:
            return pdf()
        if self is DocumentType.CSV:
            return csv()
        if self is DocumentType.YOUTUBE:
            return youtube()
        if self is DocumentType.OPENAPI:
            return openapi()
        if self is DocumentType.URL:
            return url()
        if self is DocumentType.MARKDOWN:
            return markdown()
        if self is DocumentType.FIRESTORE:
            return firestore()
        if self is DocumentType.PSYCHIC:
            return psychic()
        if self is DocumentType.GITHUB_REPOSITORY:
            return github_repository()
        if self is DocumentType.WEBPAGE:
            return webpage()
        if self is DocumentType.STRIPE:
            return stripe()
        if self is DocumentType.AIRTABLE:
            return airtable()
        if self is DocumentType.SITEMAP:
            return sitemap()
        if self is DocumentType.NOTION:
            return notion()
