# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class EmbeddingsModelProvider(str, enum.Enum):
    """
    An enumeration.
    """

    OPENAI = "OPENAI"
    AZURE_OPENAI = "AZURE_OPENAI"

    def visit(self, openai: typing.Callable[[], T_Result], azure_openai: typing.Callable[[], T_Result]) -> T_Result:
        if self is EmbeddingsModelProvider.OPENAI:
            return openai()
        if self is EmbeddingsModelProvider.AZURE_OPENAI:
            return azure_openai()
