# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import typing_extensions

from .tool_assistant_tools_code import ToolAssistantToolsCode
from .tool_assistant_tools_function import ToolAssistantToolsFunction
from .tool_assistant_tools_retrieval import ToolAssistantToolsRetrieval


class OpenAiAssistantParametersToolsItem_CodeInterpreter(ToolAssistantToolsCode):
    type: typing_extensions.Literal["code_interpreter"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class OpenAiAssistantParametersToolsItem_Retrieval(ToolAssistantToolsRetrieval):
    type: typing_extensions.Literal["retrieval"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class OpenAiAssistantParametersToolsItem_Function(ToolAssistantToolsFunction):
    type: typing_extensions.Literal["function"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


OpenAiAssistantParametersToolsItem = typing.Union[
    OpenAiAssistantParametersToolsItem_CodeInterpreter,
    OpenAiAssistantParametersToolsItem_Retrieval,
    OpenAiAssistantParametersToolsItem_Function,
]
